del system\dashboard-equip.png
del system\dashboard-hand.png
del system\photo-back.png
del system\dashboard-avatar.png
del system\state.png
del system\state_c.png
del system\card-back.png
del system\card-container.png
del system\ready.png
del system\arrow.png
del system\button\back.png
del system\button\back_shade.png
del system\button\back2.png
del system\button\button.png
del system\button\free-regulate.png
del system\button\free-regulate-disabled.png
del system\button\irregular\background.png
del system\button\frequent_checkbox\checked.png
del system\button\frequent_checkbox\checked_hover.png
del system\button\frequent_checkbox\checked_press.png
del system\button\frequent_checkbox\unchecked.png
del system\button\frequent_checkbox\unchecked_hover.png
del system\button\frequent_checkbox\unchecked_press.png
pause